if (self.CavalryLogger) { CavalryLogger.start_js(["pR7JU"]); }

__d("XStoriesAsyncTrayController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/stories/tray/async/",{expanded:{type:"Bool",defaultValue:!1}})}),null);
__d("FBStoriesTrayReloadXHPTray",["AsyncRequest","XStoriesAsyncTrayController"],(function(a,b,c,d,e,f){"use strict";a={reloadTray:function(a){a=b("XStoriesAsyncTrayController").getURIBuilder().setBool("expanded",(a=a)!=null?a:!1).getURI();new(b("AsyncRequest"))().setURI(a).setMethod("GET").setReadOnly(!0).send()}};e.exports=a}),null);
__d("XFBStoriesPermalinkController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/stories/{?bucket_id}/{?card_id}/",{bucket_id:{type:"FBID"},card_id:{type:"String"},source:{type:"String"}})}),null);
__d("persistentQueryParams",[],(function(a,b,c,d,e,f){"use strict";e.exports=["__DEV__","__pc","__xtrace__","_country_override_","artillery_sample","big_pipe","break_on_name","break_on_pass","browserlab_logging","browserlab_test","cacheobs_sample","cavalry_cohort","demo_ad","detectreflows","dpr","ego_services","egodebug","fbtrace","feed_demo_ad","flog","force_logging","force_megaphone_reload","forced_qp_id","gk_debug","gk_disable","gk_enable","gomez_sample","hide_dev_console","js_debug","js_nocatch","killabyte","locale","mh_function_visitor_off","mh_function_visitor_on","mh_p_content_refs","mh_p_function_visitor","mh_p_inline_require","mh_p_min","nobatch","nocache","no_dev_console","pagelet_ts","pagelet_whitelist","profiling_mode","public_mode","qe","qrt_version","react_log_top_level_renders","react_perf","ro_group","ro_name","rollout","se_default","se_gs","sk","sr_sourcemaps","sri","story_type","teak_sample","test_id_inspector","__tier","tlog","tti","vid","webdriver","wirehog_sample","showlog"]}),null);
__d("StoriesViewer2URI",["PageTransitions","URI","XFBStoriesPermalinkController","persistentQueryParams"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g="/stories",h="/stories/test";e.exports={isValid:function(a){a=a.getPath();return a.startsWith(g)&&!a.startsWith(h)},getURI:function(a,c){__p&&__p();var d=b("XFBStoriesPermalinkController").getURIBuilder();a!=null&&a!==""&&d.setFBID("bucket_id",a);c!=null&&c!==""&&d.setString("card_id",c);a=d.getURI();var e=b("URI").getNextURI().getQueryData(),f=new Set(Object.keys(e));c={};b("persistentQueryParams").reduce(function(a,b){f.has(b)&&(a[b]=e[b]);return a},c);a.setQueryData(c);return a},updateURL:function(a,c){if(a==null||a=="")return;if(this.isValid(b("PageTransitions").getNextURI())===!1)return;a=this.getURI(a,c);history.replaceState(null,"",a.toString())}}}),null);
__d("FBStoriesQPLUtils",["QuickPerformanceLogger","Run"],(function(a,b,c,d,e,f){"use strict";function g(a){a.navigationStart?b("QuickPerformanceLogger").markerStartFromNavStart(a.qplMarker):b("QuickPerformanceLogger").markerStart(a.qplMarker,0),b("Run").onUnload(function(){b("QuickPerformanceLogger").markerEnd(a.qplMarker,"CANCEL")})}a={start:function(a){g(a)},end:function(a){b("QuickPerformanceLogger").markerEnd(a.qplMarker,a.action?a.action:"SUCCESS")}};e.exports=a}),null);
__d("FBStoriesSettingsDialogTabType",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({ARCHIVE_SETTINGS_TAB:"archive_settings_tab",MUTED_SETTINGS_TAB:"muted_settings_tab"})}),null);
__d("StoriesArchiveQuickLogModule",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({ARCHIVE_GRID_TTI:22347781,ARCHIVE_GRID_TTI_WWW:22347782,PAGINATION_TTI:22347779,SCROLL_PERF:22347783,STORIES_VIEWER_TTI:22347777,THUMBNAIL_TTI:22347780,VIEWERS_LIST_TTI:22347778})}),null);
__d("StoriesQuickLogModule",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({CARD_DELETION:13238332,DOWNLOAD_RETRY:13238389,FB_STORY_ADMIN_PAGE_SCROLL_PERF:13238334,FB_STORY_VIEWER_LIST_SCROLL_PERF:13238335,LIGHTWEIGHT_MESSAGING_TTRC:13238347,LWR_TAP_ANIMATION_TTI:13238316,LWR_TAP_ANIMATION_TTI_WWW:13238357,MEDIA_DISPLAY_TTI:13238280,NAV_LIST_LOAD_PAGINATION_TTI_WWW:13238355,OPEN_STORIES_REPLY_IN_BLUE_FROM_JEWEL_NOTIFICATION_TTRC:13238348,OPEN_STORIES_REPLY_IN_BLUE_FROM_PUSH_NOTIFICATION_TTRC:13238349,OPEN_STORIES_REPLY_IN_BLUE_PRODUCER_INITIATED_TTRC:13238369,REPLY_BAR_TTI:13238307,ROW_COLD_START_TTI:13238277,ROW_REFRESH_TTI:13238279,STORIES_ERRORS:13238323,STORIES_SURFACE_TTRC:13238375,STORIES_TRAY_TTRC:13238320,STORIES_TTRC:13238319,STORY_DOWNLOAD_RETRY:13238388,STORY_VIEWER_BUCKET_TRANSITION_TTI_WWW:13238354,STORY_VIEWER_DEPTH_RESPONSIVENESS:13238321,STORY_VIEWER_LOAD_FIRST_TIME_WWW:13238314,STORY_VIEWER_LOAD_TTI:13238296,STORY_VIEWER_LOAD_TTI_V2_WWW:13238353,STORY_VIEWER_LOAD_TTI_WWW:13238313,STORY_VIEWER_NOTIF_ASYNC_TTI_WWW:13238374,STORY_VIEWER_NOTIF_PERMALINK_TTI_WWW:13238373,STORY_VIEWER_RESPONSIVENESS:13238312,STORY_VIEWER_SHEET_INITIAL_LOAD_TTI:13238345,STORY_VIEWER_SHEET_INITIAL_LOAD_TTRC:13238346,STORY_VIEWER_SWIPE_FPS:13238308,STORY_VIEWER_THREAD_TRANSITION_TTI_WWW:13238356,STORY_VIEWER_TRANSITION_FPS:13238311,STORY_WARM_START_TTI:13238283,SURFACE_COMPLETE_TTI:13238376,SURFACE_LOAD_PAGINATION_TTI:13238377,TRAY_COMPLETE_TTI:13238299,TRAY_LOAD_PAGINATION_TTI:13238297,TRAY_LOAD_TTI:13238293,TRAY_TTRC_WITH_IMAGES:13238325,VIEWER_FIRST_STORY_LOAD_TTI:13238273,VIEWER_NEXT_BUCKET_TTI:13238275,VIEWER_NEXT_STORY_TTI:13238274,VIEWER_SHEET_ENTRY_POINT_CONSISTENCY:13238365,VIEWER_SHEET_LOAD_TTI:13238298,VIEWER_SHEET_TTRC:13238306})}),null);